// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps, getApp } from "firebase/app";
import { getAuth } from "firebase/auth";

const firebaseConfig = {
  "projectId": "healthassist-ai-m7r1o",
  "appId": "1:100123926144:web:2c9f2adb15fd63b0435065",
  "storageBucket": "healthassist-ai-m7r1o.firebasestorage.app",
  "apiKey": "AIzaSyAbWitNj6B6BSVQtoki3OxdW3a-IKCnbxk",
  "authDomain": "healthassist-ai-m7r1o.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "100123926144"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);

export { app, auth };
